* shinyGMM
** About

shinyGMM implements a collection of R code written during prototyping for [[https://github.com/clwgg/nQuire][nQuire]]
into a interactive shiny application. It implements inference of Gaussian Mixture Models (GMM)
using either an Expectation-Maximization (EM) algorithm or a Gibbs sampler. Some
of the code was adapted from Matthew Stephens' [[https://github.com/stephens999/fiveMinuteStats][fiveMinuteStats]].

The primary purpose of this project was to be able to play around with simulations of GMMs
and how the different inference methods deal with changing parameterization. However, it also
implements an interface with ~.bin~ files generated by [[https://github.com/clwgg/nQuire][nQuire]], so real base frequency data
can be loaded. Still, it is very experimental and by no means intended for production data analysis. It
does not use the implementation of the EM algorithm used in [[https://github.com/clwgg/nQuire][nQuire]], but its R based prototype.

** Get it

Clone the repository:

#+BEGIN_SRC bash
git clone https://github.com/clwgg/shinyGMM
#+END_SRC

Compile the C plugin for nQuire ~.bin~ file integration and install all R
packages needed (these are: ~shiny~, ~magrittr~, ~dplyr~, ~tidyr~, ~ggplot2~, ~cowplot~, ~gtools~):

#+BEGIN_SRC bash
cd shinyGMM
make lib
make packages
#+END_SRC

** Usage

To run the application, use:

#+BEGIN_SRC bash
make run
#+END_SRC

At the end of the start-up procedure, there will be a link to the localhost port
where the application is listening. This should be opened in a suitable web
browser.
